name: "Deploy"
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v9
        with:
          nix_conf: experimental-features = nix-command flakes
      - name: update android sources
        run: ./scripts/update.sh
      - name: lint
        run: ./scripts/format.sh --check
      - name: test
        run: nix flake check
      - name: push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          ./scripts/deploy.sh
      - name: build nixexprs
        run: ./scripts/channel.sh
      - name: deploy nix channel
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
          SINGLE_COMMIT: true
          GIT_CONFIG_NAME: "github-actions"
          GIT_CONFIG_EMAIL: "github-actions@github.com"
      - name: main -> stable
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: stable
          github_token: ${{ github.token }}
      - name: main -> beta
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: beta
          github_token: ${{ github.token }}
      - name: main -> preview
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: preview
          github_token: ${{ github.token }}
      - name: main -> canary
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: canary
          github_token: ${{ github.token }}
